#------------------------------------------------------------------------------------------------------------------------------------
#
# Site Settings
#
# This is a YAML file which can be edited to configure the text, images, colors, and videos on the site.
#
# The basic rules of editing are as follows:
#
# 1. Structure is conveyed by indentation. Use 2 spaces to indicate that an item belongs to the parent above it.
#
# 2. Pound signs are used to mark commented lines. If a piece of text needs to include a pound or other special symbol,
#    it should be enclosed in quotation marks.
#
# 3. By default, text cannot span multiple lines. If a piece of text needs to extend over multiple lines, use the pipe character |.
#
# 4. To create visual breaks between paragraphs, use the HTML tag <br /> to start a new line. 2 of these tags will create a blank 
#    line between your paragraphs.
# 
#------------------------------------------------------------------------------------------------------------------------------------

# This is the text which will appear in a browser tab.
title: Racine Truck Sales TV Advertisements

# Message to display at the bottom of the page.
banner-message: Welcome to Kriete Truck Center Racine, Your One-Stop Provider for Parts, Service, and Sales

# Increase this value to make the text in the banner move more slowly. Be sure to include the s for seconds.
banner-time: 20.0s

# Image which will appear next to the banner message.
logo-url: logo.jpg

# Add the id for a YouTube playlist here. This will be the string of letters and numbers at the end of the url listed under the src attribute of the embed dialog.
youtube-id: PLR5EBzKgvuttnDRqi4iz4IVED5_poLTwl

# Set to true to enable video controls. Set to false to disable.
youtube-controls: false

# This list can be edited to configure the advertisements which will be displayed. It is very important that each level
# of indentation be marked with 2 spaces. A dash denotes a new item. Keep the descriptions relatively brief so that they fit.
advertisements:
  - 
    title: 2012 International Prostar
    description: <h3>$18,900</h3></br><p><strong>Call Mary at 262-483-1717 for more details</strong></p>
    image-name: 2012_International_Prostar.jpg
  - 
    title: 2010 Mack Pinnacle 70" High Rise Ultra Shift
    description: <h3>$46,900</h3></br><p><strong>Call Mary at 262-483-1717 for more details</strong></p>
    image-name: 2010_Mack_Pinnacle.jpg
  - 
    title: 2011 Mack Granite Quad
    description: <h3>$134,900</h3></br><p><strong>Call Mary at 262-483-1717 for more details</strong></p>
    image-name: 2011_Mack_Granite.jpg
  -
    title: Service Special - DataTorq
    description: <h3>Precision Wheel Torque with Printout</br>$75</h3>
    image-name: data-torq.png

  - 
    title: 2010 Volvo 730
    description: <h2>$39,900</h2>
    image-name: V281571U.JPG
  - 
    title: 2016 Volvo VNL64T670
    description: <h2>$129,900</h2>
    image-name: V94623U.jpg
  -
    title: 1994 Mack RD688P
    description: <h2>$12,900</h2>
    image-name: MAC020970U.jpg
  -
    title: 2009 Mack CXU613
    description: <h2>$38,500</h2>
    image-name: MAC7084U.jpg
  -
    title: 2009 Mack CXU613
    description: <h2>$42,900</h2>
    image-name: MAC7334u.jpg
  -
    title: 2012 Volvo VNL64T670
    description: <h2>$62,900</h2>
    image-name: V540837UA.jpg
  -
    title: 2012 Volvo VNL64T670
    description: <h2>$59,900</h2>
    image-name: V547638U-2012.jpg
  -
    title: 2012 Volvo VNL64T670
    description: <h2>$64,900</h2>
    image-name: V546458U.jpg
  -
    title: 2012 Mack CXU613
    description: <h2>$59,900</h2>
    image-name: MAC18590U-2012.jpg
  -
    title: 2012 Volvo VNL64T780
    description: <h2>$56,900</h2>
    image-name: VNL780.jpg
  -
    title: Gunite 3600AX 
    description: <h3>Heavy Duty Brake Drum</br>$74.95</h3>
    image-name: 3600ABrakeDrum.jpg
  -
    title: Gunite 3922X
    description: <h3>Standard Duty Brake Drum</br>$64.95</h3>
    image-name: 3600ABrakeDrum.jpg
  -
    title: Delco Remy Alternator
    description: <h3>New with 3 Year Warranty</h3>
    image-name: 36SI-pad-mount.png
  -
    title: Delco Remy Starter
    description: <h3>New with 3 Year Warranty</br>$189</h3>
    image-name: delco-starter.png
  -
    title: Accuride Aluminum Rim
    description: <h3>Inside/Outside Polished</br>$210</h3>
    image-name: aluminum-wheel.jpg
  -
    title: Merriter Brake Shoe Kit
    description: <h3>8235-XK2124707QP</br>$43.95</h3>
    image-name: brake-shoe-kit.JPG
  -
    title: Eaton-Spicer Clutch
    description: <h3>Easy Pedal</br>$641</h3>
    image-name: easy-pedal-clutch.jpg
  -
    title: Exide Heavy Duty Battery
    description: <h3>EXIPX31925C</br>$66</h3>
    image-name: exide925t.jpg
  -
    title: 30lb Freon
    description: <h3>R134A Refrigerant Freon</br>$78</h3>
    image-name: freon.jpg
  -
    title: Seats Incorporated Black Leather
    description: <h3>66.188900MW61</br>$640</h3>
    image-name: legacy-silver-sm.png
  -
    title: Stemco Wheel Chock
    description: <h3>STM18455</br>$17.50</h3>
    image-name: wheel-chock.JPG

# Time which each advertisement will display for. NO s FOR THIS ONE.
ad-time: 15.0

# This should be a small textured image tile which can be repeated to form a pleasing background.
# This field can be left blank if a solid color is desired.
background-url: diamond_plate.jpg

# This can be a color name like 'blue' or a hexadecimal like '#DCDFE0'.
background-color: '#DCDFE0'

# This color will be used for borders.
accent-color: '#28B3B5'



