#-------------------------------
# General Site Settings

banner-message: 'Welcome to Racine Truck Sales, Your One-Stop Provider for Parts, Service, and Sales'

title: Jordan Cannon's Design Portfolio
description: Inventor // AutoCAD // SolidWorks
email: cannonJm@msoe.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
	description: 'Provide a description for your website to make it visible to search engines.'
	rel-author:
	rel-publisher:

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X
