#-------------------------------
# General Site Settings

banner-message: Welcome to Racine Truck Sales, Your One-Stop Provider for Parts, Service, and Sales

youtube-url: https://www.youtube.com/embed/videoseries?list=PLR5EBzKgvuttnDRqi4iz4IVED5_poLTwl

advertisements: 
  - 
    title: Gears
    description: "These are gears."
    image-name: hero-bg.jpg
  - 
    title: Tires 30% Off
    description: Try out our new premium tires at a reduced rate.
    image-name: tire.jpg
  - 
    title: SXS Pro
    description: Years of research and design have gone into the creation of what is the best RZR and side by side seat in the industry. The all-new Corbeau SXS, combines everything that was missing in a quality side by side seat, with the quality and design that Corbeau is so well known for.
    image-name: seat.jpg




title: Racine Truck Sales TV Advertisements
description: 
email: 


